### ISSUE TITLE
Can't join

### ISSUE THREAD

**Issue by IkaDreeminn** [19MisterX98/SeedcrackerX#10]
So, I'm trying to do this on a modded server (it's just few origins mods), and it keeps on failing.
[](https://i.gyazo.com/dfab2ad6e325deac5625d16289f6baa0.png)

[19:08:34] [main/ERROR]: Registry remapping failed!
java.lang.RuntimeException: Server contains Fabric-modded registries: minecraft:block, minecraft:enchantment, minecraft:mob_effect, minecraft:entity_type, minecraft:item! Multiconnect does not support modded registries.
	at net.fabricmc.fabric.impl.registry.sync.RegistrySyncManager.handler$zoi000$onApplyModdedRegistry(RegistrySyncManager.java:543) [909a9447-3934-4e32-8a61-bd3110ac5259.jar:?]
	at net.fabricmc.fabric.impl.registry.sync.RegistrySyncManager.lambda$receivePacket$0(RegistrySyncManager.java) [909a9447-3934-4e32-8a61-bd3110ac5259.jar:?]
	at net.fabricmc.fabric.impl.registry.sync.RegistrySyncManager$$Lambda$4430/22956143.get(Unknown Source) [909a9447-3934-4e32-8a61-bd3110ac5259.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1582) [?:1.8.0_51]
	at net.minecraft.class_1255.method_18859(class_1255.java:191) [intermediary-fabric-loader-0.11.2-1.16.5.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) [intermediary-fabric-loader-0.11.2-1.16.5.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:153) [intermediary-fabric-loader-0.11.2-1.16.5.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:130) [intermediary-fabric-loader-0.11.2-1.16.5.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1015) [intermediary-fabric-loader-0.11.2-1.16.5.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:681) [intermediary-fabric-loader-0.11.2-1.16.5.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:215) [intermediary-fabric-loader-0.11.2-1.16.5.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226) [fabric-loader-0.11.2.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146) [fabric-loader-0.11.2.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) [fabric-loader-0.11.2.jar:?]

if this helps..

**Comment by IkaDreeminn** [comment]
![](https://i.gyazo.com/dfab2ad6e325deac5625d16289f6baa0.png)

**Comment by 19MisterX98** [comment]
That seems like a multiconnect issue. Try without it
