### ISSUE TITLE
game crash

### ISSUE THREAD

**Issue by EitanTheFirst** [19MisterX98/SeedcrackerX#102]
hi! I tried to use your mod but I have a problem, I can lunch the game with the mod on but when I enter a single-player world or a server the game just crashes. pls, fix it soon! tysm!

**Comment by Strikeout0815** [comment]
This issue happens for me too

**Comment by notpoiu** [comment]
do you have the crash report thinggy

**Comment by Strikeout0815** [comment]
No sorry. But I found a workaround. Simple delete everything in the config folder which include "Seedcracker" in its name and it should work fine again

**Comment by BigPanda97** [comment]
I got the same error, here is what you need:

`Time: 20.07.22, 12:28
Description: Unexpected error

java.lang.ExceptionInInitializerError
	at net.minecraft.class_634.handler$bhn002$onGameJoin(class_634.java:10972)
	at net.minecraft.class_634.method_11120(class_634.java:397)
	at net.minecraft.class_2678.method_11567(class_2678.java:86)
	at net.minecraft.class_2678.method_11054(class_2678.java:20)
	at net.minecraft.class_2600.method_11072(class_2600.java:22)
	at net.minecraft.class_1255.method_18859(class_1255.java:157)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.class_1255.method_16075(class_1255.java:131)
	at net.minecraft.class_1255.method_5383(class_1255.java:116)
	at net.minecraft.class_310.method_1523(class_310.java:1095)
	at net.minecraft.class_310.method_1514(class_310.java:734)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.NullPointerException
	at java.base/java.util.Objects.requireNonNull(Objects.java:208)
	at java.base/java.util.ImmutableCollections.listFromTrustedArray(ImmutableCollections.java:213)
	at java.base/java.util.List.of(List.java:979)
	at kaptainwutax.seedcrackerX.config.StructureSave.<clinit>(StructureSave.java:22)
	... 15 more`

**Comment by 19MisterX98** [comment]
The crash should be fixed in the snapshot release. It happens when you load a config from a newer mod version in an older version. You can fix it by deleting the config

**Comment by BigPanda97** [comment]
> It happens when you load a config from a newer mod version in an older version. You can fix it by deleting the config

I already used the latest version. But for some reason, after a client-restart, there was "1_12_2" in the config... I just changed that to "1_19" and restarted the client, and everything was working normally.
