### ISSUE TITLE
Error when leaving server

### ISSUE THREAD

**Issue by end-user** [19MisterX98/SeedcrackerX#103]
I get this error when I close a connection
`[08:24:59] [Render thread/INFO]: [STDERR]: java.io.IOException: Invalid file path
[08:24:59] [Render thread/INFO]: [STDERR]: 	at java.base/java.io.File.createNewFile(File.java:1041)
[08:24:59] [Render thread/INFO]: [STDERR]: 	at kaptainwutax.seedcrackerX.config.StructureSave.saveStructures(StructureSave.java:30)
[08:24:59] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_638.handler$bid000$disconnect(class_638.java:3123)
[08:24:59] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_638.method_8525(class_638.java)
...`

Am I missing a config setting or have something set wrong?

**Comment by 19MisterX98** [comment]
Are you using a custom file path for your minecraft instance or a custom launcher?

**Comment by end-user** [comment]
Yes - using MultiMC

**Comment by 19MisterX98** [comment]
Multimc is fine, maybe your worldname contains invalid characters for a file path

**Comment by end-user** [comment]
Correct, I see that there are files with world names with .txt when they're single-player, and servernames with an underscore and IP (but no extension).  Almost all these files are empty though.

**Comment by end-user** [comment]
Yes, it appears to happen for all servers, everytime, but not in single player.
