### ISSUE TITLE
Feature Request: Nether Cracking?

### ISSUE THREAD

**Issue by InternetNutzer** [19MisterX98/SeedcrackerX#116]
I noticed, that it is quite hard to crack the nether seed and I would like to ask if it is possible to 

- add bastions & fortresses or spawner positions (if this even helps with finding the seed) - since tree cracking got patched
- write possible seeds to a file, so people who really would like to find it, could search through the seeds manually if something doesn't work

**Comment by Snowad14** [comment]
bastions / fortresses does not allow you to have the seed and for trees it will always give you a lot of seeds (humanly impossible to check them all) as long as the decorator cracking is not functional

**Comment by Sp3rick** [comment]
its acutally impossible or by upgrading this mod we can get it work again?

**Comment by Snowad14** [comment]
It is possible but it would require an update that uses the graphics card and it would take several hours.
there is also the branch "NetherRoofCracker" which uses the roof of the nether but its not work on paper

**Comment by Sp3rick** [comment]
Tell me more about "NetherRoofCracker" searching on google i dont find anything

**Comment by Snowad14** [comment]
https://github.com/19MisterX98/SeedcrackerX/tree/NetherRoofCracker You need to be pretty proficient with Windows, I'm not going to give you a tutorial but basically: Build the .jar -> Install cuda & visual studio build tools having an NVIDIA graphics card -> run BedrockCracker.cu in the terminal in the fabric config folder after joining a non-paper server and it detects the bedrock when you are in the nether.

**Comment by Sp3rick** [comment]
for what minecraft version is it

**Comment by Snowad14** [comment]
I was talking about versions 1.18 and 1.19, if you want to do it in the ones below 1.18 it just takes a few seconds with the ones that are already implemented

**Comment by Sp3rick** [comment]
ok, i did everything successfull but i cant compile NetherRoofFinder.java can you give me it (.jar) pls

**Comment by Snowad14** [comment]
If you can't compile it you'll never get it to work right.I just advise you to do something else

**Comment by Sp3rick** [comment]
i compiled it and i get a 149kb file, but i think that maybe i not compiled right so its for be sure

**Comment by Sp3rick** [comment]
when i execute BedrockCracker.cu i receive 
Finished gpu: time_millis:889, output: 0, run:8
Finished gpu: time_millis:826, output: 0, run:7
Finished gpu: time_millis:826, output: 0, run:6
Finished gpu: time_millis:827, output: 0, run:5
Finished gpu: time_millis:827, output: 0, run:4
Finished gpu: time_millis:826, output: 0, run:3
Finished gpu: time_millis:827, output: 0, run:2
Finished gpu: time_millis:826, output: 0, run:1

**Comment by 19MisterX98** [comment]
usually one of them should have given you an output seed for example:

Finished gpu: time_millis:7214, output: 0, run:8
Finished gpu: time_millis:7155, output: 1, run:7
Finished gpu: time_millis:7156, output: 0, run:6
Finished gpu: time_millis:7179, output: 0, run:5
Finished gpu: time_millis:7169, output: 0, run:4
Finished gpu: time_millis:7169, output: 0, run:3
Finished gpu: time_millis:7167, output: 0, run:2
Finished gpu: time_millis:7197, output: 0, run:1

you might wanna try with a different chunk.

**Comment by Sp3rick** [comment]
> usually one of them should have given you an output seed for example:
> 
> Finished gpu: time_millis:7214, output: 0, run:8 Finished gpu: time_millis:7155, output: 1, run:7 Finished gpu: time_millis:7156, output: 0, run:6 Finished gpu: time_millis:7179, output: 0, run:5 Finished gpu: time_millis:7169, output: 0, run:4 Finished gpu: time_millis:7169, output: 0, run:3 Finished gpu: time_millis:7167, output: 0, run:2 Finished gpu: time_millis:7197, output: 0, run:1
> 
> you might wanna try with a different chunk.

mh thanks, i think that i havent correctly used the NetherRoofCracker.jar file, the fact that you have 7000 milliseconds per run and i have 800 milliseconds is maybe because is not calculating anything? anyway,  i have to put NetherRoofCracker.jar it in mods folder right?

**Comment by Snowad14** [comment]
and then you have to go into the nether and you will see that the bedrock will be highlighted

**Comment by 19MisterX98** [comment]
The time greatly depends on your gpu, i have a 1050ti.

You got the cracker to run so you must have done everything correctly.

Can you send the .cu file to check if it was populated correctly?

**Comment by Sp3rick** [comment]
> The time greatly depends on your gpu, i have a 1050ti.
> 
> You got the cracker to run so you must have done everything correctly.
> 
> Can you send the .cu file to check if it was populated correctly?
ok i uploaded the .cu file, so the fact that i got the 149kb .jar means that it is correct?
[a-out.zip](https://github.com/19MisterX98/SeedcrackerX/files/9402173/a-out.zip)

**Comment by 19MisterX98** [comment]
your jar should be around 2mb. also your cu file does not contain bedrock data

**Comment by Sp3rick** [comment]
> your jar should be around 2mb. also your cu file does not contain bedrock data

oh ok, you can send the right .cu file and .jar?

**Comment by 19MisterX98** [comment]
[seedcrackerX-2.12.zip](https://github.com/19MisterX98/SeedcrackerX/files/9402384/seedcrackerX-2.12.zip)
unzip to get the jar. github doesnt allow jar extentions

the cu file is generated by the mod.

**Comment by MakingPanorama** [comment]
I tried to use this .jar file, but I got an error:
`net.fabricmc.loader.impl.FormattedException: java.lang.ExceptionInInitializerError
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:463)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.ExceptionInInitializerError
	at net.minecraft.class_2378.<clinit>(class_2378.java:326)
	at meteordevelopment.meteorclient.systems.modules.Modules.<clinit>(Modules.java:65)
	at net.minecraft.class_128.handler$bdb000$onAddStackTrace(class_128.java:524)
	at net.minecraft.class_128.method_555(class_128.java:80)
	at net.minecraft.class_128.method_568(class_128.java:134)
	at net.minecraft.class_128.method_24305(class_128.java:274)
	at net.minecraft.client.main.Main.method_44604(Main.java:159)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	... 2 more
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_2874 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:419)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at net.minecraft.class_7231.method_42043(class_7231.java:18)
	at net.minecraft.class_5458.method_44104(class_5458.java:98)
	at net.minecraft.class_5458.method_30566(class_5458.java:105)
	at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:721)
	at net.minecraft.class_5458.<clinit>(class_5458.java:104)
	... 11 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at meteordevelopment.meteorclient.asm.Asm$Transformer.transformClassBytes(Asm.java:102)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:414)
	... 20 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [seedcracker.mixins.json:DimensionTypeMixin from mod seedcrackerx] from phase [DEFAULT] in config [seedcracker.mixins.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:589)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379)
	... 24 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: @Shadow field field_25617 was not located in the target class net.minecraft.class_2874. Using refmap seedcrackerX-refmap.json
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachFields(MixinPreProcessorStandard.java:624)
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:302)
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:277)
	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1289)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:292)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 24 more`
	
I tried to use this on 1.19.2 version

**Comment by MakingPanorama** [comment]
I tried to use this .jar file, but my minecraft crashes with that error:
net.fabricmc.loader.impl.FormattedException: java.lang.ExceptionInInitializerError
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:463)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.ExceptionInInitializerError
	at net.minecraft.class_2378.<clinit>(class_2378.java:326)
	at meteordevelopment.meteorclient.systems.modules.Modules.<clinit>(Modules.java:65)
	at net.minecraft.class_128.handler$bdb000$onAddStackTrace(class_128.java:524)
	at net.minecraft.class_128.method_555(class_128.java:80)
	at net.minecraft.class_128.method_568(class_128.java:134)
	at net.minecraft.class_128.method_24305(class_128.java:274)
	at net.minecraft.client.main.Main.method_44604(Main.java:159)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	... 2 more
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_2874 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:419)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at net.minecraft.class_7231.method_42043(class_7231.java:18)
	at net.minecraft.class_5458.method_44104(class_5458.java:98)
	at net.minecraft.class_5458.method_30566(class_5458.java:105)
	at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:721)
	at net.minecraft.class_5458.<clinit>(class_5458.java:104)
	... 11 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at meteordevelopment.meteorclient.asm.Asm$Transformer.transformClassBytes(Asm.java:102)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:414)
	... 20 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [seedcracker.mixins.json:DimensionTypeMixin from mod seedcrackerx] from phase [DEFAULT] in config [seedcracker.mixins.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:589)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379)
	... 24 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: @Shadow field field_25617 was not located in the target class net.minecraft.class_2874. Using refmap seedcrackerX-refmap.json
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachFields(MixinPreProcessorStandard.java:624)
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:302)
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:277)
	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1289)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:292)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 24 more
Launched on Minecraft 1.19.2

**Comment by MakingPanorama** [comment]
> [seedcrackerX-2.12.zip](https://github.com/19MisterX98/SeedcrackerX/files/9402384/seedcrackerX-2.12.zip) unzip to get the jar. github doesnt allow jar extentions
> 
> the cu file is generated by the mod.

Which minecraft version it works?
If it works lower 1.19.2
can you give a compiled file for actual version and higher?

I've tried it on 1.19.2, but minecraft crashes with error(i can give logs if it need)

**Comment by 19MisterX98** [comment]
I wont update the code to 1.19, It works on 1.18.2.

I think a library url changed, at least the github actions dont work anymore too
