### ISSUE TITLE
Cant run fabric loader at all due to an error with the mod

### ISSUE THREAD

**Issue by itsadt** [19MisterX98/SeedcrackerX#149]

**Comment by itsadt** [comment]
i can enter minecraft but when i try to join any server it crashes and sends


Caused by: java.lang.NullPointerException
	at java.base/java.util.Objects.requireNonNull(Objects.java:208)
	at java.base/java.util.ImmutableCollections.listFromTrustedArray(ImmutableCollections.java:213)
	at java.base/java.util.List.of(List.java:979)
	at kaptainwutax.seedcrackerX.config.StructureSave.<clinit>(StructureSave.java:22)
	... 16 more
