### ISSUE TITLE
Seedcracker 2.13 crashes in 1.19.2 when trying to access a world or joining a server. The title screen and server/world lists are unaffected, but crashes when attempting to connect to a server or fire up a singleplayer world. Can you fix this please? Thanks!

### ISSUE THREAD

**Issue by Asn-16** [19MisterX98/SeedcrackerX#171]
Crash Message:
---- Minecraft Crash Report ----
// Why did you do that?

Time: 2023-01-07 11:35:13
Description: Unexpected error

java.lang.ExceptionInInitializerError
	at net.minecraft.class_634.handler$zjh002$onGameJoin(class_634.java:4021)
	at net.minecraft.class_634.method_11120(class_634.java:416)
	at net.minecraft.class_2678.method_11567(class_2678.java:86)
	at net.minecraft.class_2678.method_11054(class_2678.java:20)
	at net.minecraft.class_2600.method_11072(class_2600.java:22)
	at net.minecraft.class_1255.method_18859(class_1255.java:157)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.class_1255.method_16075(class_1255.java:131)
	at net.minecraft.class_1255.method_5383(class_1255.java:116)
	at net.minecraft.class_310.method_1523(class_310.java:1129)
	at net.minecraft.class_310.method_1514(class_310.java:768)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.NullPointerException
	at java.base/java.util.Objects.requireNonNull(Objects.java:208)
	at java.base/java.util.ImmutableCollections.listFromTrustedArray(ImmutableCollections.java:213)
	at java.base/java.util.List.of(List.java:979)
	at kaptainwutax.seedcrackerX.config.StructureSave.<clinit>(StructureSave.java:22)
	... 16 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_634.handler$zjh002$onGameJoin(class_634.java:4021)
	at net.minecraft.class_634.method_11120(class_634.java:416)
	at net.minecraft.class_2678.method_11567(class_2678.java:86)
	at net.minecraft.class_2678.method_11054(class_2678.java:20)
	at net.minecraft.class_2600.method_11072(class_2600.java:22)
	at net.minecraft.class_1255.method_18859(class_1255.java:157)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.class_1255.method_16075(class_1255.java:131)

-- Affected level --
Details:
	All players: 1 total; [class_746['Asn16'/105042, l='ClientLevel', x=8.50, y=65.00, z=8.50]]
	Chunk stats: 361, 0
	Level dimension: minecraft:overworld
	Level spawn location: World: (8,64,8), Section: (at 8,0,8 in 0,4,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 0 game time, 0 day time
	Server brand: ~~NULL~~
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:453)
	at net.minecraft.class_310.method_1587(class_310.java:2341)
	at net.minecraft.class_310.method_1514(class_310.java:792)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods

-- System Details --
Details:
	Minecraft Version: 1.19.2
	Minecraft Version ID: 1.19.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1000068768 bytes (953 MiB) / 1476395008 bytes (1408 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: 11th Gen Intel(R) Core(TM) i7-11370H @ 3.30GHz
	Identifier: Intel64 Family 6 Model 140 Stepping 1
	Microarchitecture: Tiger Lake
	Frequency (GHz): 3.30
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: Intel(R) Iris(R) Xe Graphics
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 1024.00
	Graphics card #0 deviceId: 0x9a49
	Graphics card #0 versionInfo: DriverVersion=30.0.101.1631
	Graphics card #1 name: NVIDIA GeForce RTX 3070 Laptop GPU
	Graphics card #1 vendor: NVIDIA (0x10de)
	Graphics card #1 VRAM (MB): 4095.00
	Graphics card #1 deviceId: 0x249d
	Graphics card #1 versionInfo: DriverVersion=30.0.15.1278
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 22461.67
	Virtual memory used (MB): 16650.74
	Swap memory total (MB): 6400.00
	Swap memory used (MB): 273.64
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		fabric-api: Fabric API 0.69.0+1.19.2
			fabric-api-base: Fabric API Base 0.4.13+0d0f210290
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.12+93d8cb8290
			fabric-biome-api-v1: Fabric Biome API (v1) 9.0.20+0d0f210290
			fabric-block-api-v1: Fabric Block API (v1) 1.0.1+12bfe4ea90
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.22+c6af733c90
			fabric-client-tags-api-v1: Fabric Client Tags 1.0.3+b35fea8390
			fabric-command-api-v1: Fabric Command API (v1) 1.2.13+f71b366f90
			fabric-command-api-v2: Fabric Command API (v2) 2.1.9+93d8cb8290
			fabric-commands-v0: Fabric Commands (v0) 0.2.30+df3654b390
			fabric-containers-v0: Fabric Containers (v0) 0.1.38+df3654b390
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.4.4+6064db2a90
			fabric-convention-tags-v1: Fabric Convention Tags 1.2.0+27265b3490
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.7+aeb40ebe90
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 5.3.3+ad31814d90
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.33+0d0f210290
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.2+9244241690
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.31+6eb9a2a190
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.31+df3654b390
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.23+c6af733c90
			fabric-item-api-v1: Fabric Item API (v1) 1.6.1+fa140d5990
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.36+9244241690
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.23+aaaf9d3390
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.21+df3654b390
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.2+9244241690
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.10+83a8659290
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.13+9e7660c690
			fabric-message-api-v1: Fabric Message API (v1) 5.0.5+93d8cb8290
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.21+33fbc73890
			fabric-models-v0: Fabric Models (v0) 0.3.19+c6af733c90
			fabric-networking-api-v1: Fabric Networking API (v1) 1.2.8+3b1d070f90
			fabric-networking-v0: Fabric Networking (v0) 0.3.25+df3654b390
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 4.1.3+06e0e25190
			fabric-particles-v1: Fabric Particles (v1) 1.0.12+79adfe0a90
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.29+9244241690
			fabric-renderer-api-v1: Fabric Renderer API (v1) 1.1.0+e7aeff4590
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.6.17+aeb40ebe90
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.22+df3654b390
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.17+0d0f210290
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.9+c6af733c90
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.25+df3654b390
			fabric-rendering-v1: Fabric Rendering (v1) 1.11.1+73145abb90
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.1.1+aae9039d90
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.8.2+574a764890
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.30+b0bc9a6790
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.4+1cc24b1b90
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.1+c4f28df590
			fabric-textures-v0: Fabric Textures (v0) 1.0.22+aeb40ebe90
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.1.3+9d081d6490
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.3.2+42d99c3290
		fabricloader: Fabric Loader 0.14.12
		java: OpenJDK 64-Bit Server VM 17
		minecraft: Minecraft 1.19.2
		seedcrackerx: SeedCrackerX 2.13
			cloth-config: Cloth Config v6 7.0.65
				cloth-basic-math: cloth-basic-math 0.6.1
			com_seedfinding_latticg: latticg 1.6
			com_seedfinding_mc_biome: mc_biome b2271807a047bb43ac60c8c20ad47e315f19b9a6
			com_seedfinding_mc_core: mc_core 706e4f1b7aa6b42b3627f682a311d06280d80b5c
			com_seedfinding_mc_feature: mc_feature ef939c0dd7d66ab1bd290d6aab1e42a12cb3dbf1
			com_seedfinding_mc_math: mc_math 0eb505174da8a92550f8ec6efe254e0fa936cc0d
			com_seedfinding_mc_noise: mc_noise a6ab8e6c688491829f8d2adf845392da22ef8e9c
			com_seedfinding_mc_reversal: mc_reversal 2.0.0
			com_seedfinding_mc_seed: mc_seed 5518e3ba3ee567fb0b51c15958967f70a6a19e02
			com_seedfinding_mc_terrain: mc_terrain 9e937ddb838e28e79423c287fa18b1ce66f061d7
	Launched Version: fabric-loader-0.14.12-1.19.2
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: NVIDIA GeForce RTX 3070 Laptop GPU/PCIe/SSE2 GL version 3.2.0 NVIDIA 512.78, NVIDIA Corporation
	Window size: 1920x1080
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, Fabric Mods
	Current Language: English (US)
	CPU: 8x 11th Gen Intel(R) Core(TM) i7-11370H @ 3.30GHz

**Comment by Asn-16** [comment]
Nvm I fixed it, I deleted everything seedcracker and reinstalled. Thanks!
