### ISSUE TITLE
Crashing when join a multiplayer server

### ISSUE THREAD

**Issue by lordcenturione** [19MisterX98/SeedcrackerX#208]
Hello, so i use fabric and decided to crack the seed on a 1.19.2 modded server, when i join it just closes my minecraft and gives me a log.

---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 2023-04-01 22:30:18
Description: Unexpected error

java.lang.ExceptionInInitializerError
	at net.minecraft.class_634.handler$bol002$seedcrackerx$onGameJoin(class_634.java:6021)
	at net.minecraft.class_634.method_11120(class_634.java:416)
	at net.minecraft.class_2678.method_11567(class_2678.java:86)
	at net.minecraft.class_2678.method_11054(class_2678.java:20)
	at net.minecraft.class_2600.method_11072(class_2600.java:22)
	at net.minecraft.class_1255.method_18859(class_1255.java:157)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.class_1255.method_16075(class_1255.java:131)
	at net.minecraft.class_1255.method_5383(class_1255.java:116)
	at net.minecraft.class_310.method_1523(class_310.java:1129)
	at net.minecraft.class_310.method_1514(class_310.java:768)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.NullPointerException
	at java.base/java.util.Objects.requireNonNull(Objects.java:208)
	at java.base/java.util.ImmutableCollections.listFromTrustedArray(ImmutableCollections.java:213)
	at java.base/java.util.List.of(List.java:979)
	at kaptainwutax.seedcrackerX.config.StructureSave.<clinit>(StructureSave.java:22)
	... 16 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_634.handler$bol002$seedcrackerx$onGameJoin(class_634.java:6021)
	at net.minecraft.class_634.method_11120(class_634.java:416)
	at net.minecraft.class_2678.method_11567(class_2678.java:86)
	at net.minecraft.class_2678.method_11054(class_2678.java:20)
	at net.minecraft.class_2600.method_11072(class_2600.java:22)
	at net.minecraft.class_1255.method_18859(class_1255.java:157)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.class_1255.method_16075(class_1255.java:131)

-- Affected level --
Details:
	All players: 1 total; [class_746['Lordcen'/8234, l='ClientLevel', x=8.50, y=65.00, z=8.50]]
	Chunk stats: 841, 0
	Level dimension: minecraft:overworld
	Level spawn location: World: (8,64,8), Section: (at 8,0,8 in 0,4,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 0 game time, 0 day time
	Server brand: ~~NULL~~
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:453)
	at net.minecraft.class_310.method_1587(class_310.java:2341)
	at net.minecraft.class_310.method_1514(class_310.java:792)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods

-- System Details --
Details:
	Minecraft Version: 1.19.2
	Minecraft Version ID: 1.19.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 687090712 bytes (655 MiB) / 2147483648 bytes (2048 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 4
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i3-9100F CPU @ 3.60GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 11
	Microarchitecture: Coffee Lake
	Frequency (GHz): 3.60
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 4
	Graphics card #0 name: NVIDIA GeForce GTX 1070 Ti
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1b82
	Graphics card #0 versionInfo: DriverVersion=31.0.15.1694
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.40
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.40
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 18737.46
	Virtual memory used (MB): 15207.93
	Swap memory total (MB): 2432.00
	Swap memory used (MB): 0.00
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		backslot: BackSlot 1.2.11
			amecsapi: Amecs API 1.3.6+mc22w17a
		bclib: BCLib 2.1.6
		betterend: Better End 2.1.4
		betternether: Better Nether 7.1.3
		cloth-config: Cloth Config v8 8.2.88
			cloth-basic-math: cloth-basic-math 0.6.1
		fabric-api: Fabric API 0.76.0+1.19.2
			fabric-api-base: Fabric API Base 0.4.15+8f4e8eb390
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.14+93d8cb8290
			fabric-biome-api-v1: Fabric Biome API (v1) 9.1.1+16f1e31390
			fabric-block-api-v1: Fabric Block API (v1) 1.0.2+e415d50e90
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.25+cafc6e8e90
			fabric-client-tags-api-v1: Fabric Client Tags 1.0.5+b35fea8390
			fabric-command-api-v1: Fabric Command API (v1) 1.2.16+f71b366f90
			fabric-command-api-v2: Fabric Command API (v2) 2.2.1+413cbbc790
			fabric-commands-v0: Fabric Commands (v0) 0.2.33+df3654b390
			fabric-containers-v0: Fabric Containers (v0) 0.1.41+df3654b390
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.5.2+7c6cd14d90
			fabric-convention-tags-v1: Fabric Convention Tags 1.3.0+4bc6e26290
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.8+aeb40ebe90
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 5.3.8+413cbbc790
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.35+0d0f210290
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.4+9244241690
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.34+562bff6e90
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.36+df3654b390
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.24+b6b6abb490
			fabric-item-api-v1: Fabric Item API (v1) 1.6.6+b7d1888890
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.39+9244241690
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.25+5c4fce2890
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.23+df3654b390
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.4+1b46dc7890
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.13+83a8659290
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.16+9e7660c690
			fabric-message-api-v1: Fabric Message API (v1) 5.0.7+93d8cb8290
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.24+33fbc73890
			fabric-models-v0: Fabric Models (v0) 0.3.21+c6af733c90
			fabric-networking-api-v1: Fabric Networking API (v1) 1.2.11+10eb22f490
			fabric-networking-v0: Fabric Networking (v0) 0.3.28+df3654b390
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 4.2.2+d8ef690890
			fabric-particles-v1: Fabric Particles (v1) 1.0.14+4d0d570390
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.1+413cbbc790
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.32+9244241690
			fabric-renderer-api-v1: Fabric Renderer API (v1) 1.2.1+1adbf27790
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.8.0+1adbf27790
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.24+df3654b390
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.19+6e0787e690
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.11+4d0d570390
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.27+df3654b390
			fabric-rendering-v1: Fabric Rendering (v1) 1.12.1+d8ef690890
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.1.2+aae9039d90
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.8.4+edbdcddb90
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.32+4d0d570390
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.7+1cc24b1b90
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.2+c4f28df590
			fabric-textures-v0: Fabric Textures (v0) 1.0.24+aeb40ebe90
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.1.6+413cbbc790
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.3.3+08b73de490
		fabricloader: Fabric Loader 0.14.19
		fwaystones: Fabric Waystones 3.0.7+mc1.19.2
		java: OpenJDK 64-Bit Server VM 17
		journeymap: Journeymap 5.9.4
			journeymap-api-fabric: JourneyMap API 1.19.1-1.9-fabric-SNAPSHOT
		minecraft: Minecraft 1.19.2
		owo: oωo 0.8.5+1.19
			blue_endless_jankson: jankson 1.2.1
		philipsruins: Philip`s ruins 1.19.2
		seedcrackerx: SeedCrackerX 2.13
			com_seedfinding_latticg: latticg 1.6
			com_seedfinding_mc_biome: mc_biome b2271807a047bb43ac60c8c20ad47e315f19b9a6
			com_seedfinding_mc_core: mc_core 706e4f1b7aa6b42b3627f682a311d06280d80b5c
			com_seedfinding_mc_feature: mc_feature ef939c0dd7d66ab1bd290d6aab1e42a12cb3dbf1
			com_seedfinding_mc_math: mc_math 0eb505174da8a92550f8ec6efe254e0fa936cc0d
			com_seedfinding_mc_noise: mc_noise a6ab8e6c688491829f8d2adf845392da22ef8e9c
			com_seedfinding_mc_reversal: mc_reversal 2.0.0
			com_seedfinding_mc_seed: mc_seed 5518e3ba3ee567fb0b51c15958967f70a6a19e02
			com_seedfinding_mc_terrain: mc_terrain 9e937ddb838e28e79423c287fa18b1ce66f061d7
		twilightforest: The Twilight Forest 4.2.335
			cardinal-components-base: Cardinal Components API (base) 5.0.1
			cardinal-components-entity: Cardinal Components API (entities) 5.0.1
			com_google_code_findbugs_jsr305: jsr305 3.0.2
			forgeconfigapiport: Forge Config API Port 4.1.4
				com_electronwill_night-config_core: core 3.6.5
				com_electronwill_night-config_toml: toml 3.6.5
			here-be-no-dragons: Here be no Dragons! 1.0.0
			javax_annotation_javax_annotation-api: javax.annotation-api 1.3.2
			mm: Manningham Mills 2.3
			porting_lib: Porting Lib 2.1.727+1.19.2
				com_github_llamalad7_mixinextras: MixinExtras 0.1.1
				forge_tags: Porting Lib Tags 3.0
				porting_lib_accessors: Porting Lib Accessors 2.1.727+1.19.2
				porting_lib_attributes: Porting Lib Attributes 2.1.727+1.19.2
				porting_lib_base: Porting Lib Base 2.1.727+1.19.2
				porting_lib_common: Porting Lib Common 2.1.727+1.19.2
				porting_lib_constants: Porting Lib Constants 2.1.727+1.19.2
				porting_lib_entity: Porting Lib Entity 2.1.727+1.19.2
				porting_lib_extensions: Porting Lib Extensions 2.1.727+1.19.2
				porting_lib_fake_players: Porting Lib Fake Players 2.1.727+1.19.2
				porting_lib_lazy_registration: Porting Lib Lazy Register 2.1.727+1.19.2
				porting_lib_model_generators: Porting Lib Model Generators 2.1.727+1.19.2
				porting_lib_model_loader: Porting Lib Model Loader 2.1.727+1.19.2
				porting_lib_models: Porting Lib Models 2.1.727+1.19.2
				porting_lib_networking: Porting Lib Networking 2.1.727+1.19.2
				porting_lib_obj_loader: Porting Lib Obj Loader 2.1.727+1.19.2
				porting_lib_transfer: Porting Lib Transfer 2.1.727+1.19.2
				serialization_hooks: Serialization Hooks 0.3.26
			reach-entity-attributes: Reach Entity Attributes 2.3.0
		xaerobetterpvp: Better PVP Mod 23.3.2
	Launched Version: fabric-loader-0.14.19-1.19.2
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: NVIDIA GeForce GTX 1070 Ti/PCIe/SSE2 GL version 3.2.0 NVIDIA 516.94, NVIDIA Corporation
	Window size: 1920x1080
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, file/LowOnFire_1.19.zip, file/Better_grass_1.19.zip, Fabric Mods
	Current Language: English (US)
	CPU: 4x Intel(R) Core(TM) i3-9100F CPU @ 3.60GHz

**Comment by Dyiing** [comment]
#207
