### ISSUE TITLE
Crashes in 1.20.2

### ISSUE THREAD

**Issue by Visionnary** [19MisterX98/SeedcrackerX#270]
Every time I try to join a single player world or a server, the game just crashes when I'm loading in. I've already tried to delete the config folder and run it again but it still didn't work. Here is the crash report:

---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 2023-09-23 20:27:51
Description: Unexpected error

java.lang.NoSuchMethodError: 'long net.minecraft.class_2678.comp_96()'
	at net.minecraft.class_634.handler$zle002$seedcrackerx$onGameJoin(class_634.java:4406)
	at net.minecraft.class_634.method_11120(class_634.java:440)
	at net.minecraft.class_2678.method_11567(class_2678.java:57)
	at net.minecraft.class_2678.method_11054(class_2678.java:14)
	at net.minecraft.class_2600.method_11072(class_2600.java:23)
	at net.minecraft.class_1255.method_18859(class_1255.java:156)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.class_1255.method_16075(class_1255.java:130)
	at net.minecraft.class_1255.method_5383(class_1255.java:115)
	at net.minecraft.class_310.method_1523(class_310.java:1231)
	at net.minecraft.class_310.method_1514(class_310.java:856)
	at net.minecraft.client.main.Main.main(Main.java:253)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_634.handler$zle002$seedcrackerx$onGameJoin(class_634.java:4406)
	at net.minecraft.class_634.method_11120(class_634.java:440)
	at net.minecraft.class_2678.method_11567(class_2678.java:57)
	at net.minecraft.class_2678.method_11054(class_2678.java:14)
	at net.minecraft.class_2600.method_11072(class_2600.java:23)
	at net.minecraft.class_1255.method_18859(class_1255.java:156)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.class_1255.method_16075(class_1255.java:130)

-- Affected level --
Details:
	All players: 1 total; [class_746['WhyLeftClick'/149, l='ClientLevel', x=8.50, y=65.00, z=8.50]]
	Chunk stats: 5041, 0
	Level dimension: minecraft:the_nether
	Level spawn location: World: (8,64,8), Section: (at 8,0,8 in 0,4,0; chunk contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 0 game time, 0 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:451)
	at net.minecraft.class_310.method_1587(class_310.java:2481)
	at net.minecraft.class_310.method_1514(class_310.java:880)
	at net.minecraft.client.main.Main.main(Main.java:253)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, fabric

-- System Details --
Details:
	Minecraft Version: 1.20.2
	Minecraft Version ID: 1.20.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.8, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 662692144 bytes (631 MiB) / 1677721600 bytes (1600 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 20
	Processor Vendor: GenuineIntel
	Processor Name: 13th Gen Intel(R) Core(TM) i5-13600K
	Identifier: Intel64 Family 6 Model 183 Stepping 1
	Microarchitecture: unknown
	Frequency (GHz): 3.49
	Number of physical packages: 1
	Number of physical CPUs: 14
	Number of logical CPUs: 20
	Graphics card #0 name: NVIDIA GeForce GTX 1080
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1b80
	Graphics card #0 versionInfo: DriverVersion=31.0.15.3623
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 2.67
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.67
	Memory slot #1 type: DDR4
	Memory slot #2 capacity (MB): 16384.00
	Memory slot #2 clockSpeed (GHz): 2.67
	Memory slot #2 type: DDR4
	Memory slot #3 capacity (MB): 8192.00
	Memory slot #3 clockSpeed (GHz): 2.67
	Memory slot #3 type: DDR4
	Virtual memory max (MB): 122617.71
	Virtual memory used (MB): 31277.49
	Swap memory total (MB): 73728.00
	Swap memory used (MB): 3534.47
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		fabric-api: Fabric API 0.89.2+1.20.2
			fabric-api-base: Fabric API Base 0.4.32+fce67b32a0
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.40+fce67b32a0
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.11+86b12645a0
			fabric-block-api-v1: Fabric Block API (v1) 1.0.11+73761d2ea0
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.0+73761d2ea0
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.42+f4b7e424a0
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.3+86b12645a0
			fabric-command-api-v1: Fabric Command API (v1) 1.2.35+f71b366fa0
			fabric-command-api-v2: Fabric Command API (v2) 2.2.14+86b12645a0
			fabric-commands-v0: Fabric Commands (v0) 0.2.52+df3654b3a0
			fabric-containers-v0: Fabric Containers (v0) 0.1.71+df3654b3a0
			fabric-content-registries-v0: Fabric Content Registries (v0) 5.0.3+0ba8e9cea0
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.6+f4b7e424a0
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.19+f4b7e424a0
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 13.1.1+bbae80faa0
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.55+b1229956a0
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.24+f4b7e424a0
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.8+daef22a2a0
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.67+df3654b3a0
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.39+f4b7e424a0
			fabric-item-api-v1: Fabric Item API (v1) 2.1.31+43511215a0
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.12+f4b7e424a0
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.37+f4b7e424a0
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.35+df3654b3a0
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.25+3bafade3a0
			fabric-loot-api-v2: Fabric Loot API (v2) 2.0.1+0ba8e9cea0
			fabric-message-api-v1: Fabric Message API (v1) 6.0.0+fce67b32a0
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.53+f4b7e424a0
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.4+f4b7e424a0
			fabric-models-v0: Fabric Models (v0) 0.4.3+9386d8a7a0
			fabric-networking-api-v1: Fabric Networking API (v1) 3.0.7+74a33ae7a0
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 12.1.0+b1b4f7b0a0
			fabric-particles-v1: Fabric Particles (v1) 1.1.3+f4b7e424a0
			fabric-recipe-api-v1: Fabric Recipe API (v1) 2.0.4+43511215a0
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 4.0.2+34a3e0e2a0
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.2.0+2034447ca0
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.5.0+2034447ca0
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.47+df3654b3a0
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.38+73761d2ea0
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.29+f4b7e424a0
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.50+df3654b3a0
			fabric-rendering-v1: Fabric Rendering (v1) 3.0.9+86b12645a0
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.8+43511215a0
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.10+86b12645a0
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.10+0ba8e9cea0
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.37+86b12645a0
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.13+f4b7e424a0
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.3.7+109a65e5a0
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 5.0.2+fce67b32a0
		fabricloader: Fabric Loader 0.14.22
		java: OpenJDK 64-Bit Server VM 17
		minecraft: Minecraft 1.20.2
		seedcrackerx: SeedCrackerX 2.14.4
			cloth-config: Cloth Config v11 11.0.98
				cloth-basic-math: cloth-basic-math 0.6.1
			com_seedfinding_latticg: latticg 1.6
			com_seedfinding_mc_biome: mc_biome 41a42cb9019a552598f12089059538853e18ec78
			com_seedfinding_mc_core: mc_core d64d5f90be66300da41ef58f4f1736db2499784f
			com_seedfinding_mc_feature: mc_feature 919b7e513cc1e87e029a9cd703fc4e2dc8686229
			com_seedfinding_mc_math: mc_math ffd2edcfcc0d18147549c88cc7d8ec6cf21b5b91
			com_seedfinding_mc_noise: mc_noise 7e3ba65e181796c4a2a1c8881d840b2254b92962
			com_seedfinding_mc_reversal: mc_reversal ca64c0890c106f1a2207623c316fce86f250b918
			com_seedfinding_mc_seed: mc_seed 1ead6fcefe7e8de4b3d60cd6c4e993f1e8f33409
			com_seedfinding_mc_terrain: mc_terrain b4246cbd5880c4f8745ccb90e1b102bde3448126
	JVM uptime in seconds: 18.403
	Launched Version: fabric-loader-0.14.22-1.20.2
	Backend library: LWJGL version 3.3.2-snapshot
	Backend API: NVIDIA GeForce GTX 1080/PCIe/SSE2 GL version 3.2.0 NVIDIA 536.23, NVIDIA Corporation
	Window size: 854x480
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, fabric
	Current Language: en_us
	Locale: en_CA
	CPU: 20x 13th Gen Intel(R) Core(TM) i5-13600K
	Server Running: true
	Player Count: 1 / 8; [class_3222['WhyLeftClick'/149, l='ServerLevel[New World]', x=-1582.08, y=81.00, z=146.30]]
	Data Packs: vanilla, fabric
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable

**Comment by Ghost942** [comment]
Unable to assist with solution, but am also able to confirm failure to launch into single-player world without receiving same error code/crash log.

Perhaps there is something we are missing between 1.20.1 and 1.20.2?

Things shouldn't be that different, but there are changes regardless.
Tis simply a matter of patience and waiting for a 1.20.2 update for this mod.

**Comment by slowpoke111** [comment]
---- Minecraft Crash Report ----
// Shall we play a game?

Time: 2023-09-27 20:43:35
Description: Unexpected error

java.lang.NoSuchMethodError: 'long net.minecraft.class_2678.comp_96()'
	at net.minecraft.class_634.handler$zle002$seedcrackerx$onGameJoin(class_634.java:4406)
	at net.minecraft.class_634.method_11120(class_634.java:440)
	at net.minecraft.class_2678.method_11567(class_2678.java:57)
	at net.minecraft.class_2678.method_11054(class_2678.java:14)
	at net.minecraft.class_2600.method_11072(class_2600.java:23)
	at net.minecraft.class_1255.method_18859(class_1255.java:156)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.class_1255.method_16075(class_1255.java:130)
	at net.minecraft.class_1255.method_5383(class_1255.java:115)
	at net.minecraft.class_310.method_1523(class_310.java:1231)
	at net.minecraft.class_310.method_1514(class_310.java:856)
	at net.minecraft.client.main.Main.main(Main.java:253)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_634.handler$zle002$seedcrackerx$onGameJoin(class_634.java:4406)
	at net.minecraft.class_634.method_11120(class_634.java:440)
	at net.minecraft.class_2678.method_11567(class_2678.java:57)
	at net.minecraft.class_2678.method_11054(class_2678.java:14)
	at net.minecraft.class_2600.method_11072(class_2600.java:23)
	at net.minecraft.class_1255.method_18859(class_1255.java:156)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.class_1255.method_16075(class_1255.java:130)

-- Affected level --
Details:
	All players: 1 total; [class_746['slowpoke_12'/23541, l='ClientLevel', x=8.50, y=65.00, z=8.50]]
	Chunk stats: 289, 0
	Level dimension: minecraft:overworld
	Level spawn location: World: (8,64,8), Section: (at 8,0,8 in 0,4,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 0 game time, 0 day time
	Server brand: vanilla
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:451)
	at net.minecraft.class_310.method_1587(class_310.java:2481)
	at net.minecraft.class_310.method_1514(class_310.java:880)
	at net.minecraft.client.main.Main.main(Main.java:253)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, fabric

-- System Details --
Details:
	Minecraft Version: 1.20.2
	Minecraft Version ID: 1.20.2
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 17.0.8, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 291647872 bytes (278 MiB) / 771751936 bytes (736 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 16
	Processor Vendor: GenuineIntel
	Processor Name: 13th Gen Intel(R) Core(TM) i7-13700HX
	Identifier: Intel64 Family 6 Model 191 Stepping 2
	Microarchitecture: unknown
	Frequency (GHz): 2.30
	Number of physical packages: 1
	Number of physical CPUs: 16
	Number of logical CPUs: 24
	Graphics card #0 name: NVIDIA GeForce RTX 4060 Laptop GPU
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x28a0
	Graphics card #0 versionInfo: DriverVersion=31.0.15.3667
	Graphics card #1 name: Intel(R) UHD Graphics
	Graphics card #1 vendor: Intel Corporation (0x8086)
	Graphics card #1 VRAM (MB): 1024.00
	Graphics card #1 deviceId: 0x4688
	Graphics card #1 versionInfo: DriverVersion=31.0.101.4502
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 4.80
	Memory slot #0 type: Unknown
	Memory slot #1 capacity (MB): 16384.00
	Memory slot #1 clockSpeed (GHz): 4.80
	Memory slot #1 type: Unknown
	Virtual memory max (MB): 37325.49
	Virtual memory used (MB): 25943.13
	Swap memory total (MB): 4864.00
	Swap memory used (MB): 134.38
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		fabric-api: Fabric API 0.89.2+1.20.2
			fabric-api-base: Fabric API Base 0.4.32+fce67b32a0
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.40+fce67b32a0
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.11+86b12645a0
			fabric-block-api-v1: Fabric Block API (v1) 1.0.11+73761d2ea0
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.0+73761d2ea0
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.42+f4b7e424a0
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.3+86b12645a0
			fabric-command-api-v1: Fabric Command API (v1) 1.2.35+f71b366fa0
			fabric-command-api-v2: Fabric Command API (v2) 2.2.14+86b12645a0
			fabric-commands-v0: Fabric Commands (v0) 0.2.52+df3654b3a0
			fabric-containers-v0: Fabric Containers (v0) 0.1.71+df3654b3a0
			fabric-content-registries-v0: Fabric Content Registries (v0) 5.0.3+0ba8e9cea0
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.6+f4b7e424a0
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.19+f4b7e424a0
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 13.1.1+bbae80faa0
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.55+b1229956a0
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.24+f4b7e424a0
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.8+daef22a2a0
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.67+df3654b3a0
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.39+f4b7e424a0
			fabric-item-api-v1: Fabric Item API (v1) 2.1.31+43511215a0
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.12+f4b7e424a0
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.37+f4b7e424a0
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.35+df3654b3a0
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.25+3bafade3a0
			fabric-loot-api-v2: Fabric Loot API (v2) 2.0.1+0ba8e9cea0
			fabric-message-api-v1: Fabric Message API (v1) 6.0.0+fce67b32a0
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.53+f4b7e424a0
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.4+f4b7e424a0
			fabric-models-v0: Fabric Models (v0) 0.4.3+9386d8a7a0
			fabric-networking-api-v1: Fabric Networking API (v1) 3.0.7+74a33ae7a0
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 12.1.0+b1b4f7b0a0
			fabric-particles-v1: Fabric Particles (v1) 1.1.3+f4b7e424a0
			fabric-recipe-api-v1: Fabric Recipe API (v1) 2.0.4+43511215a0
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 4.0.2+34a3e0e2a0
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.2.0+2034447ca0
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.5.0+2034447ca0
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.47+df3654b3a0
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.38+73761d2ea0
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.29+f4b7e424a0
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.50+df3654b3a0
			fabric-rendering-v1: Fabric Rendering (v1) 3.0.9+86b12645a0
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.8+43511215a0
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.10+86b12645a0
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.10+0ba8e9cea0
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.37+86b12645a0
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.13+f4b7e424a0
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.3.7+109a65e5a0
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 5.0.2+fce67b32a0
		fabricloader: Fabric Loader 0.14.22
		java: OpenJDK 64-Bit Server VM 17
		minecraft: Minecraft 1.20.2
		seedcrackerx: SeedCrackerX 2.14.4
			cloth-config: Cloth Config v11 11.0.98
				cloth-basic-math: cloth-basic-math 0.6.1
			com_seedfinding_latticg: latticg 1.6
			com_seedfinding_mc_biome: mc_biome 41a42cb9019a552598f12089059538853e18ec78
			com_seedfinding_mc_core: mc_core d64d5f90be66300da41ef58f4f1736db2499784f
			com_seedfinding_mc_feature: mc_feature 919b7e513cc1e87e029a9cd703fc4e2dc8686229
			com_seedfinding_mc_math: mc_math ffd2edcfcc0d18147549c88cc7d8ec6cf21b5b91
			com_seedfinding_mc_noise: mc_noise 7e3ba65e181796c4a2a1c8881d840b2254b92962
			com_seedfinding_mc_reversal: mc_reversal ca64c0890c106f1a2207623c316fce86f250b918
			com_seedfinding_mc_seed: mc_seed 1ead6fcefe7e8de4b3d60cd6c4e993f1e8f33409
			com_seedfinding_mc_terrain: mc_terrain b4246cbd5880c4f8745ccb90e1b102bde3448126
	JVM uptime in seconds: 87.808
	Launched Version: fabric-loader-0.14.22-1.20.2
	Backend library: LWJGL version 3.3.2-snapshot
	Backend API: NVIDIA GeForce RTX 4060 Laptop GPU/PCIe/SSE2 GL version 3.2.0 NVIDIA 536.67, NVIDIA Corporation
	Window size: 1920x991
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, fabric
	Current Language: en_us
	Locale: en_US
	CPU: 24x 13th Gen Intel(R) Core(TM) i7-13700HX

**Comment by Ghost942** [comment]
Suggest closing this ticket, as version 2.15.4 has released for 1.20.2 MC version
