### ISSUE TITLE
1.20.4 crashing bug w/ gui 

### ISSUE THREAD

**Issue by CrackedGlass83** [19MisterX98/SeedcrackerX#277]
**_Every command on /seedcracker either is not a "known command" or makes the game crash

I have an error code from the crash and also the error code from the launcher attached below_**

---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 2023-12-13 17:09:11
Description: Ticking entity

java.lang.IncompatibleClassChangeError: class me.shedaniel.clothconfig2.gui.entries.DropdownBoxEntry$DefaultSelectionTopCellElement$1 overrides final method net.minecraft.class_339.method_25394(Lnet/minecraft/class_332;IIF)V
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:160)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:355)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	at me.shedaniel.clothconfig2.impl.builders.DropdownMenuBuilder$TopCellElementBuilder.of(DropdownMenuBuilder.java:180)
	at me.shedaniel.clothconfig2.impl.builders.DropdownMenuBuilder$TopCellElementBuilder.of(DropdownMenuBuilder.java:176)
	at kaptainwutax.seedcrackerX.config.ConfigScreen.getConfigScreenByCloth(ConfigScreen.java:65)
	at kaptainwutax.seedcrackerX.cracker.storage.DataStorage.tick(DataStorage.java:72)
	at net.minecraft.class_746.handler$znm001$seedcrackerx$tick(class_746.java:1819)
	at net.minecraft.class_746.method_5773(class_746.java)
	at net.minecraft.class_638.method_18646(class_638.java:277)
	at net.minecraft.class_1937.method_18472(class_1937.java:492)
	at net.minecraft.class_638.method_32124(class_638.java:260)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_638.method_18116(class_638.java:256)
	at net.minecraft.class_310.method_1574(class_310.java:2011)
	at net.minecraft.class_310.method_1523(class_310.java:1289)
	at net.minecraft.class_310.method_1514(class_310.java:888)
	at net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:160)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:355)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	at me.shedaniel.clothconfig2.impl.builders.DropdownMenuBuilder$TopCellElementBuilder.of(DropdownMenuBuilder.java:180)
	at me.shedaniel.clothconfig2.impl.builders.DropdownMenuBuilder$TopCellElementBuilder.of(DropdownMenuBuilder.java:176)
	at kaptainwutax.seedcrackerX.config.ConfigScreen.getConfigScreenByCloth(ConfigScreen.java:65)
	at kaptainwutax.seedcrackerX.cracker.storage.DataStorage.tick(DataStorage.java:72)
	at net.minecraft.class_746.handler$znm001$seedcrackerx$tick(class_746.java:1819)
	at net.minecraft.class_746.method_5773(class_746.java)
	at net.minecraft.class_638.method_18646(class_638.java:277)
	at net.minecraft.class_1937.method_18472(class_1937.java:492)
	at net.minecraft.class_638.method_32124(class_638.java:260)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_638.method_18116(class_638.java:256)

-- Entity being ticked --
Details:
	Entity Type: minecraft:player (net.minecraft.class_746)
	Entity ID: 64264
	Entity Name: divorcedtony
	Entity's Exact location: 408.71, 161.00, -66.96
	Entity's Block location: World: (408,161,-67), Section: (at 8,1,13 in 25,10,-5; chunk contains blocks 400,-64,-80 to 415,319,-65), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,-64,-512 to 511,319,-1)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: null
Stacktrace:
	at net.minecraft.class_1937.method_18472(class_1937.java:492)
	at net.minecraft.class_638.method_32124(class_638.java:260)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_638.method_18116(class_638.java:256)
	at net.minecraft.class_310.method_1574(class_310.java:2011)
	at net.minecraft.class_310.method_1523(class_310.java:1289)
	at net.minecraft.class_310.method_1514(class_310.java:888)
	at net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Uptime --
Details:
	JVM uptime: 355.253s
	Wall uptime: 334.251s
	High-res time: 329.961s
	Client ticks: 6449 ticks / 322.450s
Stacktrace:
	at net.minecraft.class_310.method_1587(class_310.java:2564)
	at net.minecraft.class_310.method_54580(class_310.java:995)
	at net.minecraft.class_310.method_1514(class_310.java:908)
	at net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Affected level --
Details:
	All players: 1 total; [class_746['divorcedtony'/64264, l='ClientLevel', x=408.71, y=161.00, z=-66.96]]
	Chunk stats: 1024, 145
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,107,0), Section: (at 0,11,0 in 0,6,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 5582629 game time, 7932688 day time
	Server brand: vanilla
	Server type: Non-integrated multiplayer server
	Tracked entity count: 67

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, fabric

-- System Details --
Details:
	Minecraft Version: 1.20.4
	Minecraft Version ID: 1.20.4
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 17.0.8, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 396883184 bytes (378 MiB) / 838860800 bytes (800 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 12
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 5600H with Radeon Graphics         
	Identifier: AuthenticAMD Family 25 Model 80 Stepping 0
	Microarchitecture: Zen 3
	Frequency (GHz): 3.29
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: Virtual Desktop Monitor
	Graphics card #0 vendor: Virtual Desktop, Inc.
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: DriverVersion=15.39.56.845
	Graphics card #1 name: DisplayLink USB Device
	Graphics card #1 vendor: DisplayLink (0x17e9)
	Graphics card #1 VRAM (MB): 0.00
	Graphics card #1 deviceId: 0x4305
	Graphics card #1 versionInfo: DriverVersion=9.3.3324.0
	Graphics card #2 name: DisplayLink USB Device
	Graphics card #2 vendor: DisplayLink (0x17e9)
	Graphics card #2 VRAM (MB): 0.00
	Graphics card #2 deviceId: 0x4305
	Graphics card #2 versionInfo: DriverVersion=9.3.3324.0
	Graphics card #3 name: NVIDIA GeForce RTX 3050 Ti Laptop GPU
	Graphics card #3 vendor: NVIDIA (0x10de)
	Graphics card #3 VRAM (MB): 4095.00
	Graphics card #3 deviceId: 0x25a0
	Graphics card #3 versionInfo: DriverVersion=31.0.15.3758
	Graphics card #4 name: AMD Radeon(TM) Graphics
	Graphics card #4 vendor: Advanced Micro Devices, Inc. (0x1002)
	Graphics card #4 VRAM (MB): 512.00
	Graphics card #4 deviceId: 0x1638
	Graphics card #4 versionInfo: DriverVersion=30.0.13002.23
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 21422.25
	Virtual memory used (MB): 16235.35
	Swap memory total (MB): 5681.95
	Swap memory used (MB): 35.01
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		bettermounthud: Better Mount HUD 1.2.2
		detailab: Detail Armor Bar 2.6.3+1.20.4-fabric
		enhanced_attack_indicator: Enhanced Attack Indicator 1.0.4+1.20.3
		fabric-api: Fabric API 0.91.1+1.20.4
			fabric-api-base: Fabric API Base 0.4.34+f31bf88132
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.44+9468a19d32
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.14+9468a19d32
			fabric-block-api-v1: Fabric Block API (v1) 1.0.13+73761d2e32
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.2+73761d2e32
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.44+f4b7e42432
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.5+86b1264532
			fabric-command-api-v1: Fabric Command API (v1) 1.2.39+f71b366f32
			fabric-command-api-v2: Fabric Command API (v2) 2.2.18+23e8616e32
			fabric-commands-v0: Fabric Commands (v0) 0.2.56+df3654b332
			fabric-containers-v0: Fabric Containers (v0) 0.1.80+df3654b332
			fabric-content-registries-v0: Fabric Content Registries (v0) 5.0.8+9468a19d32
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.8+9468a19d32
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.21+f4b7e42432
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 13.1.16+1b2a41bc32
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.59+a2e8758a32
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.26+9468a19d32
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.13+9468a19d32
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.70+df3654b332
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.44+6f7ba8f232
			fabric-item-api-v1: Fabric Item API (v1) 2.1.33+9468a19d32
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.19+f6e85ac232
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.39+f4b7e42432
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.37+df3654b332
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.28+9468a19d32
			fabric-loot-api-v2: Fabric Loot API (v2) 2.1.3+6f9f09e032
			fabric-message-api-v1: Fabric Message API (v1) 6.0.3+ebb1549632
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.58+f4b7e42432
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.6+9468a19d32
			fabric-models-v0: Fabric Models (v0) 0.4.5+9386d8a732
			fabric-networking-api-v1: Fabric Networking API (v1) 3.1.1+901470e432
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 13.0.6+a2e8758a32
			fabric-particles-v1: Fabric Particles (v1) 1.1.5+f4b7e42432
			fabric-recipe-api-v1: Fabric Recipe API (v1) 2.0.14+23e8616e32
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 4.0.12+9468a19d32
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.2.2+2034447c32
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.5.2+2034447c32
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.49+df3654b332
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.40+73761d2e32
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.31+f4b7e42432
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.52+df3654b332
			fabric-rendering-v1: Fabric Rendering (v1) 3.0.11+9468a19d32
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.12+de5c6cca32
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.14+f31bf88132
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.15+f6e85ac232
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.49+9468a19d32
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.15+f4b7e42432
			fabric-transfer-api-v1: Fabric Transfer API (v1) 4.0.5+aaf9c96932
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 5.0.12+1b2a41bc32
		fabric-language-kotlin: Fabric Language Kotlin 1.10.16+kotlin.1.9.21
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.9.21
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.9.21
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.9.21
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.9.21
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.23.1
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.7.3
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.7.3
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.1
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.6.2
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.6.2
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.6.2
		fabricloader: Fabric Loader 0.15.1
			mixinextras: MixinExtras 0.3.1
		held-item-info: Held Item Info 1.5.0
		inventoryprofilesnext: Inventory Profiles Next 1.10.9
		java: OpenJDK 64-Bit Server VM 17
		libipn: libIPN 4.0.1
		minecraft: Minecraft 1.20.4
		modmenu: Mod Menu 9.0.0-pre.1
		nvidium: Nvidium 0.2.4-beta
		puzzle: Puzzle 1.6.1+1.20.4
			midnightlib: MidnightLib 1.5.2
			puzzle-base: Puzzle Base 1.6.1+1.20.4
			puzzle-gui: Puzzle GUI 1.6.1+1.20.4
			puzzle-models: Puzzle Models 1.6.1+1.20.4
			puzzle-splashscreen: Puzzle Splash Screen 1.6.1+1.20.4
		seedcrackerx: SeedCrackerX 2.14.5
			cloth-config: Cloth Config v12 12.0.109
				cloth-basic-math: cloth-basic-math 0.6.1
			com_seedfinding_latticg: latticg 1.6
			com_seedfinding_mc_biome: mc_biome 41a42cb9019a552598f12089059538853e18ec78
			com_seedfinding_mc_core: mc_core 144493514fc9bfb735ce21838e48426625f29e43
			com_seedfinding_mc_feature: mc_feature 919b7e513cc1e87e029a9cd703fc4e2dc8686229
			com_seedfinding_mc_math: mc_math ffd2edcfcc0d18147549c88cc7d8ec6cf21b5b91
			com_seedfinding_mc_noise: mc_noise 7e3ba65e181796c4a2a1c8881d840b2254b92962
			com_seedfinding_mc_reversal: mc_reversal ca64c0890c106f1a2207623c316fce86f250b918
			com_seedfinding_mc_seed: mc_seed 1ead6fcefe7e8de4b3d60cd6c4e993f1e8f33409
			com_seedfinding_mc_terrain: mc_terrain b4246cbd5880c4f8745ccb90e1b102bde3448126
		sodium: Sodium 0.5.5
		sodium-extra: Sodium Extra 0.5.3+mc1.20.2-build.114
			caffeineconfig: CaffeineConfig 1.3.0+1.17
			crowdin-translate: CrowdinTranslate 1.4+1.19.3
		sort: Sort 1.0.3
		sound_physics_remastered: Sound Physics Remastered 1.20.4-1.3.0
		status-effect-bars: Status Effect Bars 1.0.4
		wurst: Wurst Client v7.39.1-MC1.20.4
	Launched Version: fabric-loader-0.15.1-1.20.4
	Launcher name: minecraft-launcher
	Backend library: LWJGL version 3.3.2-snapshot
	Backend API: NVIDIA GeForce RTX 3050 Ti Laptop GPU/PCIe/SSE2 GL version 3.2.0 NVIDIA 537.58, NVIDIA Corporation
	Window size: 1920x1080
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Universe: 400921fb54442d18
	Type: Client (map_client.txt)
	Graphics mode: fast
	Render Distance: 5/16 chunks
	Resource Packs: vanilla, fabric
	Current Language: en_us
	Locale: en_AU
	CPU: 12x AMD Ryzen 5 5600H with Radeon Graphics 
	
	_**As well as**_

the exit code -1

and "The game crashed whilst ticking entity
Error: java.lang.IncompatibleClassChangeError: class me.shedaniel.clothconfig2.gui.entries.DropdownBoxEntry$DefaultSelectionTopCellElement$1 overrides final method net.minecraft.class_339.method_25394(Lnet/minecraft/class_332;IIF)V" from the launcher

Any bug fixing/updates on the latest versions of minecraft would be awesome :) 👍

**Comment by yggysusugysvugugsv** [comment]
Can't help but same thing is happening to me

**Comment by jxxyys** [comment]
This is also happening to me. All the other seedcracker commands work except /seedcracker gui. This command crashes minecraft and brings me back to launcher.
