### ISSUE TITLE
Seedcrackerx is not compatible with Client commands

### ISSUE THREAD

**Issue by RayyanSheik** [19MisterX98/SeedcrackerX#307]
Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Replace mod 'Client Commands' (clientcommands) 2.8.14 with any version that is compatible with:
		 - seedcrackerx 2.14.6
More details:
	 - Mod 'Client Commands' (clientcommands) 2.8.14 is incompatible with any version of mod 'SeedCrackerX' (seedcrackerx), but a matching version is present: 2.14.6!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:195)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by krispyking24** [comment]
if they knew the cause they would have already fixed it given how many people both here and in earth's discord asked about it
