### ISSUE TITLE
incompatiable

### ISSUE THREAD

**Issue by Archeumaki** [19MisterX98/SeedcrackerX#317]
what should i do???

**Comment by Archeumaki** [comment]
it said
Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Replace mod 'MultiConnect' (multiconnect) 1.5.11 with any version that is compatible with:
		 - minecraft 1.21.1
	 - Replace mod 'SeedCrackerX' (seedcrackerx) 2.14.7 with any version that is compatible with:
		 - minecraft 1.21.1
More details:
	 - Mod 'MultiConnect' (multiconnect) 1.5.11 requires any version between 1.18 (inclusive) and 1.18.1 (inclusive) of 'Minecraft' (minecraft), but only the wrong version is present: 1.21.1!
	 - Mod 'SeedCrackerX' (seedcrackerx) 2.14.7 requires version 1.20.6 of 'Minecraft' (minecraft), but only the wrong version is present: 1.21.1!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:196)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
when i copied the error

**Comment by random2048** [comment]
MultiConnect doesnt support 1.21.1, you should try [ViaFabricPlus](https://modrinth.com/mod/viafabricplus) instead. Also you are using the wrong SeedCrackerX version. You should click the **+22 releases** button under the 1.20.6 release and download the Prerelease Build (seedcrackerX-2.15.0.jar)

**Comment by Archeumaki** [comment]
i'll try that later

**Comment by Archeumaki** [comment]
could you perhaps show me how on discord if you have it?
